### ISSUE TITLE
Doesn't accept midnight as end of day

### ISSUE THREAD

**Issue by scruss** [houseabsolute/DateTime-Format-ISO8601#10]
`2020-07-24T24:00` is valid input for ISO-8601 < 2019 but is not accepted. You'll still find it generated in datalogging and billing applications.

**Comment by autarch** [comment]
The latest spec (2019) does explicitly forbid this, so I don't know that it's a good idea to add this.

**Comment by scruss** [comment]
Up to you. But the “[Standards Document](https://github.com/houseabsolute/DateTime-Format-ISO8601#standards-document)” cited in the reference is the 2000 release where hour 24 is supported.

(Not your code in particular, but this change in the standard is going to break *so much* power utility code when it ever makes it into billing systems. International train arrivals and certain military rosters use hours ≥ 24 to avoid off-by-ones in accounting.)
